services:
  mongodb:
    image: mongo:3.4.24-xenial
    volumes:
      - ./storage/mongodb:/data/db:z
  redis:
    image: redis:alpine
    volumes:
      - ./storage/redis:/data:z
  hpfeeds3:
    image: stingar/hpfeeds3:1.9
    ports:
      - "10000:10000"
  mnemosyne:
    image: stingar/mnemosyne:1.9

  chnserver:
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - ./config/collector:/etc/collector:z
      - ./storage/chnserver/sqlite:/opt/sqlite:z
      - ./certs:/tls:z
    depends_on:
      - mongodb:mongodb
      - redis:redis
      - hpfeeds3:hpfeeds3
    ports:
      - "80:80"
      - "443:443"
