services:
  victim-dynamic:
    build:
      context: .
    container_name: dynamic-victim
    ports:
      - "5002:5000"
    networks:
      victim-network:
        aliases:
          - dynamic-victim
    # Setting hardware limits
    mem_limit: 256m 
    deploy:
      resources:
        limits:
          cpus: "0.5"
    restart: always

networks:
  victim-network:
    external: true
