services:
  victim-static:
    image: nginx:latest
    container_name: static-victim
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./logs:/var/log/nginx
    networks:
      victim-network:
        aliases:
          - static-victim
    # Putting hardware limits
    mem_limit: 256m
    deploy:
      resources:
        limits:
          cpus: "0.5"
    restart: always

networks:
  victim-network:
    external: true
