services:
  victim-baseline:
    build:
      context: .
    container_name: baseline-victim
    ports:
      - "5001:5000"
    networks:
      victim-network:
        aliases:
          - baseline-victim
    # Putting hardware limits
    mem_limit: 256m 
    deploy:
      resources:
        limits:
          cpus: "0.5"
    restart: always
    
networks:
  victim-network:
    external: true
