services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - chn-network
      - victim-network
    restart: always

networks:
  chn-network:
    external: true
  victim-network:
    external: true  
